server.port=8080

spring.datasource.url=${DATA_SOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME:root}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${DATASOURCE_DRIVER_CLASS_NAME:org.mariadb.jdbc.Driver}

spring.jackson.serialization.INDENT_OUTPUT=true

# Logging
logging.level.com.chatbi=INFO
logging.level.dev.langchain4j=DEBUG
logging.pattern.console="%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

kubernetes.client.master-url=${K8S_MASTER_URL:https://127.0.0.1:6443}
kubernetes.client.oauth-token=${K8S_OAUTH_TOKEN:}
kubernetes.client.username=${K8S_USERNAME:}
kubernetes.client.password=${K8S_PASSWORD:}
kubernetes.client.trust-certs=${K8S_TRUST_CERTS:true}
kubernetes.client.namespace=${K8S_NAMESPACE:default}
